name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Check current directory
        run: pwd

      - name: Debug - List repository contents
        run: ls -R

      - name: Debug - Check gradlew permissions
        run: ls -l gradlew

      # Если ls -l gradlew не показывает 'x' (executable), раскомментируйте следующую строку
      # - name: Make gradlew executable
      #   run: chmod +x gradlew

      - name: Debug - Check gradle-wrapper.jar integrity
        run: |
          if [ -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar exists. Checking its type and size:"
            file gradle/wrapper/gradle-wrapper.jar
            du -h gradle/wrapper/gradle-wrapper.jar
            # Попробуйте перечислить содержимое JAR, чтобы убедиться, что класс внутри
            unzip -l gradle/wrapper/gradle-wrapper.jar | grep org/gradle/wrapper/GradleWrapperMain.class || echo "GradleWrapperMain.class not found in JAR"
          else
            echo "ERROR: gradle-wrapper.jar does not exist!"
          fi

      - name: Set up JDK 11 (as per your log)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        # Если ваш Gradle проект находится в поддиректории (например, 'my-project'),
        # используйте working-directory: './my-project' или 'cd my-project && ./gradlew build'
        run: ./gradlew build
        # working-directory: ./your-project-subdirectory # Раскомментируйте, если нужно
